-- ============================================================================
-- 001_INIT_TOKEN_STORE.sql
-- CRM Token Persistence Schema - Phase 1
-- PostgreSQL 13+
-- Created: 2026-03-23
-- ============================================================================

-- ============================================================================
-- 1. CORE IDENTITY TABLE
-- ============================================================================

CREATE TABLE IF NOT EXISTS users (
  userid UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  username VARCHAR(255) NOT NULL UNIQUE,
  org_name VARCHAR(255),
  email VARCHAR(255),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  
  CONSTRAINT email_format CHECK (email IS NULL OR email ~ '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}$')
);

CREATE INDEX idx_users_username ON users(username);
CREATE INDEX idx_users_email ON users(email);

-- ============================================================================
-- 2. ENCRYPTION KEY VERSIONING
-- ============================================================================

CREATE TABLE IF NOT EXISTS encryption_keys (
  key_id INTEGER PRIMARY KEY,
  key_hash VARCHAR(128) NOT NULL UNIQUE,
  algorithm VARCHAR(50) NOT NULL DEFAULT 'AES-256-GCM',
  key_version INTEGER NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  retired_at TIMESTAMP WITH TIME ZONE
);

-- Insert initial encryption key (placeholder - will be generated by app)
INSERT INTO encryption_keys (key_id, key_hash, algorithm, key_version, is_active, created_at)
VALUES (1, 'placeholder_hash_v1', 'AES-256-GCM', 1, TRUE, NOW())
ON CONFLICT (key_id) DO NOTHING;

-- ============================================================================
-- 3. MERGE API ACCOUNTS (Phase 1 Focus)
-- ============================================================================

CREATE TABLE IF NOT EXISTS merge_accounts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  userid UUID NOT NULL REFERENCES users(userid) ON DELETE CASCADE,
  
  -- Token storage
  token_ciphertext TEXT NOT NULL,
  token_key_version INTEGER NOT NULL REFERENCES encryption_keys(key_id),
  
  -- Account metadata
  account_name VARCHAR(255),
  external_account_id VARCHAR(255),
  
  -- Status tracking
  status VARCHAR(50) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'revoked', 'expired', 'invalid')),
  
  -- Timestamps
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  last_used_at TIMESTAMP WITH TIME ZONE,
  expires_at TIMESTAMP WITH TIME ZONE,
  
  CONSTRAINT unique_merge_token_per_user UNIQUE (userid, external_account_id)
);

CREATE INDEX idx_merge_accounts_userid ON merge_accounts(userid);
CREATE INDEX idx_merge_accounts_external_account_id ON merge_accounts(external_account_id);
CREATE INDEX idx_merge_accounts_status ON merge_accounts(status);
CREATE INDEX idx_merge_accounts_last_used_at ON merge_accounts(last_used_at);

-- ============================================================================
-- 4. HUBSPOT ACCOUNTS (Future Ready)
-- ============================================================================

CREATE TABLE IF NOT EXISTS hubspot_accounts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  userid UUID NOT NULL REFERENCES users(userid) ON DELETE CASCADE,
  
  token_ciphertext TEXT NOT NULL,
  token_key_version INTEGER NOT NULL REFERENCES encryption_keys(key_id),
  
  account_name VARCHAR(255),
  external_account_id VARCHAR(255),
  
  status VARCHAR(50) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'revoked', 'expired', 'invalid')),
  
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  last_used_at TIMESTAMP WITH TIME ZONE,
  expires_at TIMESTAMP WITH TIME ZONE,
  
  CONSTRAINT unique_hubspot_token_per_user UNIQUE (userid, external_account_id)
);

CREATE INDEX idx_hubspot_accounts_userid ON hubspot_accounts(userid);
CREATE INDEX idx_hubspot_accounts_external_account_id ON hubspot_accounts(external_account_id);
CREATE INDEX idx_hubspot_accounts_status ON hubspot_accounts(status);

-- ============================================================================
-- 5. UNIFIED AUDIT TRAIL
-- ============================================================================

CREATE TABLE IF NOT EXISTS token_audit_logs (
  log_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  userid UUID NOT NULL REFERENCES users(userid) ON DELETE CASCADE,
  
  -- Event tracking
  event_type VARCHAR(50) NOT NULL CHECK (event_type IN ('token_created', 'token_rotated', 'token_used', 'token_revoked', 'token_expired', 'token_error', 'status_changed')),
  provider VARCHAR(50) NOT NULL CHECK (provider IN ('merge', 'hubspot', 'salesforce', 'pipedrive')),
  account_id UUID,
  external_account_id VARCHAR(255),
  
  -- Details
  action_details JSONB,
  error_message TEXT,
  http_status_code INTEGER,
  
  -- Metadata
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  ip_address INET,
  user_agent VARCHAR(500)
);

CREATE INDEX idx_audit_logs_userid ON token_audit_logs(userid);
CREATE INDEX idx_audit_logs_provider ON token_audit_logs(provider);
CREATE INDEX idx_audit_logs_event_type ON token_audit_logs(event_type);
CREATE INDEX idx_audit_logs_created_at ON token_audit_logs(created_at);
CREATE INDEX idx_audit_logs_external_account_id ON token_audit_logs(external_account_id);

-- ============================================================================
-- 6. HELPER VIEWS
-- ============================================================================

CREATE OR REPLACE VIEW v_active_user_accounts AS
SELECT 
  u.userid, 
  u.username, 
  u.email,
  'merge' AS provider,
  ma.id AS account_id,
  ma.account_name,
  ma.external_account_id,
  ma.status,
  ma.last_used_at,
  ma.expires_at
FROM users u
INNER JOIN merge_accounts ma ON u.userid = ma.userid
WHERE ma.status = 'active'

UNION ALL

SELECT 
  u.userid, 
  u.username, 
  u.email,
  'hubspot' AS provider,
  ha.id AS account_id,
  ha.account_name,
  ha.external_account_id,
  ha.status,
  ha.last_used_at,
  ha.expires_at
FROM users u
INNER JOIN hubspot_accounts ha ON u.userid = ha.userid
WHERE ha.status = 'active';

-- ============================================================================
-- SCHEMA COMPLETE
-- ============================================================================
